name: Docker Build

on:
  push:
    branches:
      - main
      - master

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build containers
        run: docker compose build

      - name: compose up containers
        run: docker compose up -d

      - name: Test API
        run: curl localhost:3000/api